checks:
    python:
        code_rating: true
        duplicate_code: true

build:
    dependencies:
        before:
            - pip3 install -r requirements.txt
            - npm i -g eslint
    environment:
        python: 3.9.6
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                    - pylint-run
                    -
                        command: tox
                        environment: { PYTHONPATH:  }
                        coverage:
                            file: '.coverage'
                            format: 'py-cc'
        tests: true

filter:
    excluded_paths:
        - '*/tests/*'
    dependency_paths:
        - 'lib/*'

