name: "Weekly Integration Test"

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 21 * * 6'
jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install Deps
        run: dnf install -y tmt
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute test
        run: tmt -c distro=fedora run --all provision --how=local
